[package]
name = "rshtml-transpiler"
version = "0.1.0"
edition = "2024"
description = "Template transpiler and virtual Rust context generator with expression enrichment"

[dependencies]
rshtml-signature = { path = "../rshtml-signature" }
rshtml_core = { version = "0.6.1", path = "../../../rshtml/rshtml_core" }
tree-sitter = "0.25.6"

[dev-dependencies]
tree-sitter-rshtml = { git = "https://github.com/rshtml/tree-sitter-rshtml.git", tag = "v0.1.6" }
