use quote::ToTokens;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct StructFieldInfo {
    pub name: String,
    #[serde(rename = "type")]
    pub field_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TemplateMetadata {
    pub struct_name: String,
    pub template_path: String,
    #[serde(default)]
    pub impl_generics: Option<String>,
    #[serde(default)]
    pub ty_generics: Option<String>,
    #[serde(default)]
    pub where_clause: Option<String>,
    #[serde(default)]
    pub fields: Vec<StructFieldInfo>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedViewContext {
    pub struct_name: String,
    pub impl_generics: Option<String>,
    pub ty_generics: Option<String>,
    pub where_clause: Option<String>,
    pub rust_file_path: PathBuf,
    pub use_statements: Vec<String>,
    pub fields: Vec<StructFieldInfo>,
}

pub struct SignatureResolver;

impl SignatureResolver {
    /// Loads view metadata generated by `rshtml_macro` from `target/rshtml/metadata/` if available.
    pub fn load_metadata(
        workspace_root: &Path,
        template_relative_path: &str,
    ) -> Option<TemplateMetadata> {
        let meta_path = workspace_root
            .join("target")
            .join("rshtml")
            .join("metadata")
            .join(format!("{}.json", template_relative_path));

        if !meta_path.exists() {
            return None;
        }

        let content = fs::read_to_string(&meta_path).ok()?;
        serde_json::from_str(&content).ok()
    }

    /// Resolves the Rust file, struct name, generics, and inherited `use` imports for a given template path.
    pub fn resolve(
        workspace_root: &Path,
        template_relative_path: &str,
    ) -> Option<ResolvedViewContext> {
        let metadata = Self::load_metadata(workspace_root, template_relative_path);
        let src_dir = workspace_root.join("src");
        if !src_dir.exists() {
            return None;
        }

        let target_path_normalized = template_relative_path.replace('\\', "/");
        let (file_path, struct_name, impl_gen, ty_gen, where_cl, uses) =
            Self::scan_src_for_template(&src_dir, &target_path_normalized).or_else(|| {
                if let Some(ref meta) = metadata {
                    Self::scan_src_for_struct_name(&src_dir, &meta.struct_name)
                } else {
                    None
                }
            })?;

        // Prioritize metadata if present, else fallback to AST parsed generics
        let (final_impl_gen, final_ty_gen, final_where_cl) = if let Some(ref meta) = metadata {
            (
                meta.impl_generics.clone().or(impl_gen),
                meta.ty_generics.clone().or(ty_gen),
                meta.where_clause.clone().or(where_cl),
            )
        } else {
            (impl_gen, ty_gen, where_cl)
        };

        Some(ResolvedViewContext {
            struct_name,
            impl_generics: final_impl_gen,
            ty_generics: final_ty_gen,
            where_clause: final_where_cl,
            rust_file_path: file_path,
            use_statements: uses,
            fields: metadata.map(|m| m.fields).unwrap_or_default(),
        })
    }

    fn scan_src_for_template(
        src_dir: &Path,
        template_path: &str,
    ) -> Option<(
        PathBuf,
        String,
        Option<String>,
        Option<String>,
        Option<String>,
        Vec<String>,
    )> {
        let mut rust_files = Vec::new();
        Self::collect_rust_files(src_dir, &mut rust_files);

        for file in rust_files {
            if let Ok(content) = fs::read_to_string(&file) {
                if let Some((struct_name, impl_gen, ty_gen, where_cl)) =
                    Self::find_struct_with_template_attr(&content, template_path)
                {
                    let uses = Self::extract_use_statements(&content);
                    return Some((file, struct_name, impl_gen, ty_gen, where_cl, uses));
                }
            }
        }
        None
    }

    fn scan_src_for_struct_name(
        src_dir: &Path,
        expected_struct: &str,
    ) -> Option<(
        PathBuf,
        String,
        Option<String>,
        Option<String>,
        Option<String>,
        Vec<String>,
    )> {
        let mut rust_files = Vec::new();
        Self::collect_rust_files(src_dir, &mut rust_files);

        for file in rust_files {
            if let Ok(content) = fs::read_to_string(&file) {
                if let Some((found_name, impl_gen, ty_gen, where_cl)) =
                    Self::find_struct_by_name(&content, expected_struct)
                {
                    let uses = Self::extract_use_statements(&content);
                    return Some((file, found_name, impl_gen, ty_gen, where_cl, uses));
                }
            }
        }
        None
    }

    fn collect_rust_files(dir: &Path, results: &mut Vec<PathBuf>) {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    Self::collect_rust_files(&path, results);
                } else if path.extension().is_some_and(|ext| ext == "rs") {
                    results.push(path);
                }
            }
        }
    }

    /// Searches a Rust file for a struct annotated with `#[view(path = "<template_path>", ...)]`.
    /// Returns `(struct_name, impl_generics, ty_generics, where_clause)`.
    pub fn find_struct_with_template_attr(
        content: &str,
        template_path: &str,
    ) -> Option<(String, Option<String>, Option<String>, Option<String>)> {
        let parsed = syn::parse_file(content).ok()?;
        for item in parsed.items {
            if let syn::Item::Struct(item_struct) = item {
                for attr in &item_struct.attrs {
                    if attr.path().is_ident("view") {
                        let mut matches_path = false;
                        let _ = attr.parse_nested_meta(|meta| {
                            if meta.path.is_ident("path") {
                                let value = meta.value()?;
                                let s: syn::LitStr = value.parse()?;
                                if s.value() == template_path {
                                    matches_path = true;
                                }
                            }
                            Ok(())
                        });

                        if matches_path {
                            let (impl_gen, ty_gen, where_cl) =
                                Self::extract_generics(&item_struct.generics);
                            return Some((
                                item_struct.ident.to_string(),
                                impl_gen,
                                ty_gen,
                                where_cl,
                            ));
                        }
                    }
                }
            }
        }
        None
    }

    /// Finds a struct by its identifier and extracts its generics via AST.
    pub fn find_struct_by_name(
        content: &str,
        expected_struct: &str,
    ) -> Option<(String, Option<String>, Option<String>, Option<String>)> {
        let parsed = syn::parse_file(content).ok()?;
        for item in parsed.items {
            if let syn::Item::Struct(item_struct) = item {
                if item_struct.ident == expected_struct {
                    let (impl_gen, ty_gen, where_cl) =
                        Self::extract_generics(&item_struct.generics);
                    return Some((item_struct.ident.to_string(), impl_gen, ty_gen, where_cl));
                }
            }
        }
        None
    }

    fn extract_generics(
        generics: &syn::Generics,
    ) -> (Option<String>, Option<String>, Option<String>) {
        if generics.params.is_empty() && generics.where_clause.is_none() {
            return (None, None, None);
        }

        let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();

        let impl_str = impl_generics.to_token_stream().to_string();
        let ty_str = ty_generics.to_token_stream().to_string();
        let where_str = where_clause
            .map(|w| w.to_token_stream().to_string())
            .unwrap_or_default();

        let impl_opt = if impl_str.trim().is_empty() {
            None
        } else {
            Some(impl_str.trim().to_string())
        };
        let ty_opt = if ty_str.trim().is_empty() {
            None
        } else {
            Some(ty_str.trim().to_string())
        };
        let where_opt = if where_str.trim().is_empty() {
            None
        } else {
            Some(where_str.trim().to_string())
        };

        (impl_opt, ty_opt, where_opt)
    }

    /// Extracts file-level `use ...;` statements to inherit traits and types in the virtual projection.
    pub fn extract_use_statements(content: &str) -> Vec<String> {
        let mut uses = Vec::new();
        if let Ok(parsed) = syn::parse_file(content) {
            for item in parsed.items {
                if let syn::Item::Use(item_use) = item {
                    uses.push(item_use.to_token_stream().to_string());
                }
            }
        }
        uses
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_use_statements() {
        let code = r#"
use std::collections::HashMap;
use axum::{
    Router,
    response::Html,
};

pub struct Foo;
"#;
        let uses = SignatureResolver::extract_use_statements(code);
        assert_eq!(uses.len(), 2);
        assert!(uses[0].contains("std :: collections :: HashMap"));
        assert!(uses[1].contains("axum"));
    }

    #[test]
    fn test_find_struct_with_template_attr() {
        let code = r#"
#[derive(View)]
#[view(path = "views/index.rs.html", extract)]
pub struct IndexPage {
    pub title: String,
}
"#;
        let found = SignatureResolver::find_struct_with_template_attr(code, "views/index.rs.html");
        assert!(found.is_some());
        let (name, impl_gen, ty_gen, where_cl) = found.unwrap();
        assert_eq!(name, "IndexPage");
        assert_eq!(impl_gen, None);
        assert_eq!(ty_gen, None);
        assert_eq!(where_cl, None);
    }

    #[test]
    fn test_find_struct_with_generics_and_where() {
        let code = r#"
#[derive(View)]
#[view(path = "views/table.rs.html")]
pub struct TableView<'a, T: std::fmt::Display, U>
where
    U: Clone,
{
    pub items: &'a [T],
    pub config: U,
}
"#;
        let found = SignatureResolver::find_struct_with_template_attr(code, "views/table.rs.html");
        assert!(found.is_some());
        let (name, impl_gen, ty_gen, where_cl) = found.unwrap();
        assert_eq!(name, "TableView");
        assert!(
            impl_gen
                .unwrap()
                .contains("< 'a , T : std :: fmt :: Display , U >")
        );
        assert!(ty_gen.unwrap().contains("< 'a , T , U >"));
        assert!(where_cl.unwrap().contains("where U : Clone"));
    }

    #[test]
    fn test_find_struct_with_different_path() {
        let code = r#"
#[derive(View)]
#[view(path = "views/admin.rs.html")]
pub struct AdminPage;
"#;
        let found = SignatureResolver::find_struct_with_template_attr(code, "views/index.rs.html");
        assert_eq!(found, None);
    }
}
