use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct StructFieldInfo {
    pub name: String,
    #[serde(rename = "type")]
    pub field_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TemplateMetadata {
    pub struct_name: String,
    pub template_path: String,
    #[serde(default)]
    pub impl_generics: Option<String>,
    #[serde(default)]
    pub ty_generics: Option<String>,
    #[serde(default)]
    pub where_clause: Option<String>,
    #[serde(default)]
    pub fields: Vec<StructFieldInfo>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedViewContext {
    pub struct_name: String,
    pub rust_file_path: PathBuf,
    pub use_statements: Vec<String>,
    pub fields: Vec<StructFieldInfo>,
}

pub struct SignatureResolver;

impl SignatureResolver {
    /// Loads view metadata generated by `rshtml_macro` from `target/rshtml/metadata/` if available.
    pub fn load_metadata(workspace_root: &Path, template_relative_path: &str) -> Option<TemplateMetadata> {
        let meta_path = workspace_root
            .join("target")
            .join("rshtml")
            .join("metadata")
            .join(format!("{}.json", template_relative_path));

        if !meta_path.exists() {
            return None;
        }

        let content = fs::read_to_string(&meta_path).ok()?;
        serde_json::from_str(&content).ok()
    }

    /// Resolves the Rust file, struct name, and inherited `use` imports for a given template path.
    /// Matches the exact attribute signature `#[view(path = "...")]` to avoid collisions
    /// across different modules with structs sharing the same name.
    pub fn resolve(workspace_root: &Path, template_relative_path: &str) -> Option<ResolvedViewContext> {
        let metadata = Self::load_metadata(workspace_root, template_relative_path);
        let src_dir = workspace_root.join("src");
        if !src_dir.exists() {
            return None;
        }

        let target_path_normalized = template_relative_path.replace('\\', "/");
        let (file_path, struct_name, uses) = Self::scan_src_for_template(&src_dir, &target_path_normalized)
            .or_else(|| {
                // If not matched by explicit attribute path, fallback to struct name from metadata
                if let Some(ref meta) = metadata {
                    Self::scan_src_for_struct_name(&src_dir, &meta.struct_name)
                } else {
                    None
                }
            })?;

        Some(ResolvedViewContext {
            struct_name,
            rust_file_path: file_path,
            use_statements: uses,
            fields: metadata.map(|m| m.fields).unwrap_or_default(),
        })
    }

    fn scan_src_for_template(src_dir: &Path, template_path: &str) -> Option<(PathBuf, String, Vec<String>)> {
        let mut rust_files = Vec::new();
        Self::collect_rust_files(src_dir, &mut rust_files);

        for file in rust_files {
            if let Ok(content) = fs::read_to_string(&file) {
                if let Some(struct_name) = Self::find_struct_with_template_attr(&content, template_path) {
                    let uses = Self::extract_use_statements(&content);
                    return Some((file, struct_name, uses));
                }
            }
        }
        None
    }

    fn scan_src_for_struct_name(src_dir: &Path, expected_struct: &str) -> Option<(PathBuf, String, Vec<String>)> {
        let mut rust_files = Vec::new();
        Self::collect_rust_files(src_dir, &mut rust_files);

        for file in rust_files {
            if let Ok(content) = fs::read_to_string(&file) {
                if Self::contains_struct_definition(&content, expected_struct) {
                    let uses = Self::extract_use_statements(&content);
                    return Some((file, expected_struct.to_string(), uses));
                }
            }
        }
        None
    }

    fn collect_rust_files(dir: &Path, results: &mut Vec<PathBuf>) {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    Self::collect_rust_files(&path, results);
                } else if path.extension().is_some_and(|ext| ext == "rs") {
                    results.push(path);
                }
            }
        }
    }

    /// Searches a Rust file content for a struct annotated with `#[view(path = "<template_path>", ...)]`.
    pub fn find_struct_with_template_attr(content: &str, template_path: &str) -> Option<String> {
        let lines: Vec<&str> = content.lines().collect();
        for (i, line) in lines.iter().enumerate() {
            let trimmed = line.trim();
            if trimmed.starts_with("#[view(") && trimmed.contains("path =") {
                let normalized = trimmed.replace(' ', "");
                let search_needle = format!("path=\"{}\"", template_path);
                if normalized.contains(&search_needle) {
                    for next_line in &lines[i + 1..] {
                        let next_trimmed = next_line.trim();
                        if next_trimmed.starts_with("#[") {
                            continue;
                        }
                        if let Some(struct_name) = Self::parse_struct_name(next_trimmed) {
                            return Some(struct_name);
                        }
                    }
                }
            }
        }
        None
    }

    pub fn contains_struct_definition(content: &str, struct_name: &str) -> bool {
        for line in content.lines() {
            if let Some(found) = Self::parse_struct_name(line.trim()) {
                if found == struct_name {
                    return true;
                }
            }
        }
        false
    }

    fn parse_struct_name(line: &str) -> Option<String> {
        let tokens: Vec<&str> = line.split_whitespace().collect();
        for (i, token) in tokens.iter().enumerate() {
            if *token == "struct" && i + 1 < tokens.len() {
                let name = tokens[i + 1]
                    .trim_matches(|c: char| !c.is_alphanumeric() && c != '_');
                if !name.is_empty() {
                    return Some(name.to_string());
                }
            }
        }
        None
    }

    /// Extracts file-level `use ...;` statements to inherit traits and types in the virtual projection.
    pub fn extract_use_statements(content: &str) -> Vec<String> {
        let mut uses = Vec::new();
        let mut in_use = false;
        let mut current_stmt = String::new();

        for line in content.lines() {
            let trimmed = line.trim();
            if !in_use && trimmed.starts_with("use ") {
                in_use = true;
                current_stmt.clear();
            }

            if in_use {
                if !current_stmt.is_empty() {
                    current_stmt.push(' ');
                }
                current_stmt.push_str(trimmed);
                if trimmed.ends_with(';') {
                    uses.push(current_stmt.clone());
                    in_use = false;
                    current_stmt.clear();
                }
            }
        }
        uses
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_use_statements() {
        let code = r#"
use std::collections::HashMap;
use axum::{
    Router,
    response::Html,
};

pub struct Foo;
"#;
        let uses = SignatureResolver::extract_use_statements(code);
        assert_eq!(uses.len(), 2);
        assert_eq!(uses[0], "use std::collections::HashMap;");
        assert!(uses[1].starts_with("use axum::{"));
    }

    #[test]
    fn test_find_struct_with_template_attr() {
        let code = r#"
#[derive(View)]
#[view(path = "views/index.rs.html", extract)]
pub struct IndexPage {
    pub title: String,
}
"#;
        let found = SignatureResolver::find_struct_with_template_attr(code, "views/index.rs.html");
        assert_eq!(found, Some("IndexPage".to_string()));
    }

    #[test]
    fn test_find_struct_with_different_path() {
        let code = r#"
#[derive(View)]
#[view(path = "views/admin.rs.html")]
pub struct AdminPage;
"#;
        let found = SignatureResolver::find_struct_with_template_attr(code, "views/index.rs.html");
        assert_eq!(found, None);
    }

    #[test]
    fn test_resolve_with_mock_workspace() {
        use std::fs;
        let temp_dir = std::env::temp_dir().join(format!("rshtml_test_ws_{}", std::process::id()));
        let src_dir = temp_dir.join("src");
        fs::create_dir_all(&src_dir).unwrap();

        let rust_code = r#"
use chrono::{DateTime, Datelike, Utc};
use rshtml::View;

#[derive(View)]
#[view(path = "views/index.rs.html")]
pub struct IndexPage {
    pub home_time: DateTime<Utc>,
}
"#;
        fs::write(src_dir.join("main.rs"), rust_code).unwrap();

        let resolved = SignatureResolver::resolve(&temp_dir, "views/index.rs.html");
        assert!(resolved.is_some());

        let ctx = resolved.unwrap();
        assert_eq!(ctx.struct_name, "IndexPage");
        assert!(ctx.rust_file_path.ends_with("src/main.rs"));
        assert!(ctx.use_statements.iter().any(|u| u.contains("chrono")));

        let _ = fs::remove_dir_all(temp_dir);
    }
}
